export const REGISTER_EXIT = "REGISTER_EXIT"
export const REGISTER_ERROR = "REGISTER_ERROR"



export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_ERROR = "LOGIN_ERROR"

export const LOGOUT = "LOGOUT"

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

export const SHOW_ALERT = "SHOW_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"

export const UPLOAD_FIEL = "UPLOAD_FIEL"
export const UPLOAD_FIEL_SUCCESS = "UPLOAD_FIEL_SUCCESS"
export const UPLOAD_FIEL_ERROR = "UPLOAD_FIEL_ERROR"

export const UPLOAD_LINK_SUCCESS = "UPLOAD_LINK_SUCCESS"
export const UPLOAD_LINK_ERROR = "UPLOAD_LINK_ERROR"

export const CLEAR_STATE= "CLEAR_STATE"


export const ADD_PASSWORD = "ADD_PASSWORD"
export const ADD_DOWNLOAD = "ADD_DOWNLOAD"